### ISSUE TITLE
SMP Demo code files

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/INET-Vagrant-Demos#3]
The SMP_Demo directory does not have the corresponding code files.

**Comment by willow19** [comment]
Can't see the SMP_Demo directory. Has it been removed?

**Comment by prasadtalasila** [comment]
Yes. The repo has been branched with Rachit_Nov2015 containing the snapshot of the repo as valid at the end of I-Semester, 2015-16. The master branch has all the verified and functioning demos.

The SMP_Demo of Rachit_Nov2015 branch does not have the source code files. It only has the executable files. I think starting from the source code is a good experience for the learner. If possible, please put in the source code and redo the Vagrant file. This demo can follow along the lines of Nonce_Demo. Once it is found to be working, a commit can be made to the main branch.

Thanks for looking into this, Rachit.

**Comment by willow19** [comment]
I completely agree sir. SMP_Demo code is of a previous batch. They had not included the source code and had submitted only the executables.

**Comment by prasadtalasila** [comment]
I will look at another submission from that batch. Thanks.
